name:                Portalese
version:             0.1.0.0
github:              "ThibautHH/Portalese"
license:             MIT
author:              "Thibaut Hebert--Henriette"
maintainer:          "thibaut_hbt@hotmail.fr"
copyright:           "Thibaut Hebert--Henriette"

spec-version:        0.37.0

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis:            C-based language with extra features and a runtime environment
category:            Programming language

description:         Please see the README on GitHub at <https://github.com/ThibautHH/Portalese#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  glados:
    main:                GLaDOS.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is GLaDOS
    dependencies:
      - Portalese
  asec:
    main:                ASEC.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is ASEC
    dependencies:
      - Portalese

tests:
  glados-tests:
    main:                Main.hs
    source-dirs:         test/GLaDOS
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Portalese
  asec-tests:
    main:                Main.hs
    source-dirs:         test/ASEC
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Portalese
